version: '3.8'

services:
  # Database Service
  db:
    image: postgres:15-alpine
    container_name: phony-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Phony-API Service
  app:
    build: .
    container_name: phony-api
    restart: always
    ports:
      - "8081:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT:-8080}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      APP_BASE_URL: ${APP_BASE_URL:-http://localhost:8080}
    depends_on:
      - db

volumes:
  postgres_data: